#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx --no -- commitlint --edit
npx pretty-quick --staged
npx lint-staged

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright.... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

npm run build ||
(
    echo '❌👷🔨❌ Better call Your Overpowered Friends... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why.
    '
    false;
)


echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅';
